# This is a basic workflow to help you get started with Actions

name: Tester

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ play ]
  pull_request:
    branches: [ play ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo test, and deploy your project.
          pip install boto3
          export REGION=us-west-2
          export CHANNEL_TABLE_NAME=channels-134507892782-dev
          export AWS_ACCESS_KEY_ID=${{ secrets.MEITOU_AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.MEITOU_AWS_SECRET_ACCESS_KEY }}
          ls util
          python util/dynamo_test.py
  
